const books = [
  "Tinker, Tailer, Soldier, Spy",
  // "Moby Dick",
  // "God of Small Things",
  // "The Bell Jar",
  // "To Kill a Mockingbird",
  // "Life of Pi",
  // "Things Fall Apart",
  // "Oliver Twist",
  // "The Kite Runner",
  // "Jane Eyre",
  // "One Hundred Years of Solitude",
  // "The Book Theif",
  // "Watchmen",
  // "The Sun also Rises",
  // "Slaughterhouse Five",
  // "The Picture of Dorian Gray",
  // "The Odyssey",
  // "The Alchemist",
  // "The Great Gatsby",
  // "The Catcher in the Rye",
  // "The Girl with the Drgaon Tattoo",
  // "A Christmas Carol",
  // "Anna Karenina",
  // "Siddhartha",
  // "A Clockwork Orange",
  // "Crime and Punishment",
  // "The Shining",
  // "Of Mice and Men",
  // "The Metamorphosis",
];
export default books;
